# Generated by Django 2.2.17 on 2020-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='way',
            name='gain',
            field=models.IntegerField(default=0),
        ),
    ]
